/*
========================================================================================
    PREPARE_MULTIQC_CONFIG Module
========================================================================================
    Generates MultiQC configuration file with sample renaming and report header info
*/

process PREPARE_MULTIQC_CONFIG {
    label 'process_single'
    executor 'local'

    input:
    val(sample_info)      // List of maps with: fli, sample_name, species
    val(project_name)
    val(application)

    output:
    path("multiqc_config.yaml"), emit: config

    script:
    // Build sample rename entries using regex patterns to handle R1/R2 suffixes
    // Each sample gets two entries: one for _1 (R1) and one for _2 (R2)
    def rename_entries = sample_info.collect { info ->
        def base_name = info.sample_name ?: info.fli
        def species_suffix = info.species ? " (${info.species})" : ""

        // Create regex patterns that match the sample ID with _1 or _2 suffix
        // The pattern escapes special regex characters in the sample ID
        def escaped_fli = info.fli.replaceAll('([\\[\\](){}.*+?^\\$\\\\|])', '\\\\$1')

        def entries = []
        entries << "    '${escaped_fli}_1': '${base_name}_R1${species_suffix}'"
        entries << "    '${escaped_fli}_2': '${base_name}_R2${species_suffix}'"
        // Also add entry for files without _1/_2 suffix (like kraken2 reports)
        entries << "    '${escaped_fli}\$': '${base_name}${species_suffix}'"
        entries.join('\n')
    }.join('\n')

    // Build header info
    def header_items = []
    if (project_name) {
        header_items << "    - Project: '${project_name}'"
    }
    if (application) {
        header_items << "    - Application: '${application}'"
    }
    def header_section = header_items ? "report_header_info:\n${header_items.join('\n')}" : ""

    // Calculate top_n for Kraken2 plot (number of samples + 5)
    def kraken_top_n = sample_info.size() + 5

    """
    cat <<EOF > multiqc_config.yaml
# MultiQC configuration generated by BasicQC pipeline
title: "${project_name ?: 'BasicQC'} Report"
subtitle: "${application ?: 'Quality Control Analysis'}"

${header_section}

# Sample name cleaning and renaming
sample_names_replace_regex: true
sample_names_replace:
${rename_entries}

# Disable default sample name cleaning (it's too aggressive)
# and only apply our specific patterns
fn_clean_exts:
    - '.gz'
    - '.fastq'
    - '.fq'
    - '_classified.kraken2.report'
    - '.kraken2.report'
    - '.kraken2.output'
    - '_fastqc'
    - '_screen'
    - '.txt'
    - '.zip'
    - '.html'

# Disable default trimming patterns that strip after underscores
fn_clean_trim: []

# Show the General Stats table at the top of the report
show_analysis_paths: False
show_analysis_time: False

# Module order - custom content first to ensure General Stats columns appear
module_order:
    - custom_content
    - fastqc
    - fastq_screen
    - sortmerna
    - kraken

# Kraken2 plot configuration - show enough species for all samples
kraken:
    top_n: ${kraken_top_n}

# Table columns configuration - explicitly show our custom columns
table_columns_visible:
    FastQC:
        percent_duplicates: True
        percent_gc: True
        avg_sequence_length: True
        percent_fails: False
        total_sequences: True
    SortMeRNA:
        pct_rRNA: True
        rRNA: False
        non_rRNA: False
    "Custom content: kraken2_top_species_mqc":
        percent_classified: True
        top_genus: True
        percent_top_genus: True
        top_species: True
        percent_top_species: True
    "Custom content: sex_determination_mqc":
        inferred_sex: True
        sex_confidence: True

# Column ordering - put our custom columns first
table_columns_placement:
    SortMeRNA:
        pct_rRNA: 95
    "Custom content: kraken2_top_species_mqc":
        percent_classified: 100
        top_genus: 110
        percent_top_genus: 120
        top_species: 130
        percent_top_species: 140
    "Custom content: sex_determination_mqc":
        inferred_sex: 150
        sex_confidence: 160

# Hide the default Kraken module entirely from general stats
# We use our custom kraken2_summary_mqc.txt instead
skip_generalstats:
    - kraken

# General settings
log_filesize_limit: 2000000000
EOF
    """
}
